Fix #971: Implement auditing for Next Step identity
wultra/powerauth-webflow pull request #1015
Opened 2021-06-04 13:00 UTC by romanstrobl

2021-06-07 16:53 UTC, petrdvorak requested changes
I am not sure if we should replicate logging into audit log for everything that we log. Specifically, any technical issues of our service should probably not go into the audit log.

The purpose of the audit log is to store **business relevant data**, basically the user activity in our system. The user of the data in this table is a non-technical worker responsible for ad-hoc task investigation.

2021-06-07 16:53 UTC, petrdvorak commented on powerauth-nextstep/src/main/java/io/getlime/security/powerauth/app/nextstep/exception/DefaultExceptionResolver.java
> +        audit.error("Error occurred in Next Step server", AUDIT_DETAIL_UNEXPECTED_ERROR, t);
I am not sure if we want to audit all exceptions - there are already stored in logger appender and do not represent the business logic situation as much as application errors. The purpose of audit log is to store business audit (what the user was doing in the system), not technical logging.

2021-06-07 16:53 UTC, petrdvorak commented on powerauth-tpp-engine/src/main/java/io/getlime/security/powerauth/app/tppengine/errorhandling/DefaultExceptionResolver.java
>          logger.error("Error occurred in TPP engine server", t);
... same as above.

2021-06-07 16:53 UTC, petrdvorak commented on powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/errorhandling/MobileApiExceptionResolver.java
> +        audit.warn("Error occurred in Mobile Token API component", AUDIT_DETAIL_BAD_REQUEST, t);
dtto

2021-06-07 16:53 UTC, petrdvorak commented on powerauth-webflow-authentication/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/exception/AuthenticationExceptionResolver.java
> +        audit.warn("Error occurred in Web Flow server: {}", AUDIT_DETAIL_BAD_REQUEST, ex);
dtto

2021-06-07 16:53 UTC, petrdvorak commented on powerauth-webflow/src/main/java/io/getlime/security/powerauth/app/webflow/exception/DefaultExceptionResolver.java
> +        audit.error("Error occurred in Web Flow server", AUDIT_DETAIL_UNEXPECTED_ERROR, t);
dtto

2021-06-07 20:33 UTC, romanstrobl commented
In general I do agree that technical messages should not appear in audit records. However my issue with not saving the error records is that the audit trail would not provide enough information in case there is an unexpected error - the audit trail stops suddenly. But I do not feel strongly about this, we can either remove the error audits pr switch them to debug (prefered by me). As experienced many times when investigating client issues more information is usually better as long as we do not waste DB space.

2021-06-08 16:00 UTC, romanstrobl commented
As discussed offline, we will keep the error audit records for now due to their importance during investigation of what happened.

2021-06-10 18:45 UTC, merged